#!/usr/bin/env python3
"""
Test mist_archive Python module reading binary files written by C++.

Usage: python test_mist_archive.py <binary_dir>

The binary files are generated by write_test_binaries.cpp, built by CMake.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "mist"))
import mist_archive as ma


def test_vector_string(binary_dir: Path):
    print("Testing vector<string>... ", end="", flush=True)
    data = ma.load_binary(binary_dir / "test_vector_string.bin")
    assert data["products"] == ["default", "primitive", "conserved"]
    print("PASSED")


def test_vector_string_empty(binary_dir: Path):
    print("Testing vector<string> (empty)... ", end="", flush=True)
    data = ma.load_binary(binary_dir / "test_vector_string_empty.bin")
    assert data["products"] == []
    print("PASSED")


def test_nested_vector_string(binary_dir: Path):
    print("Testing nested vector<string>... ", end="", flush=True)
    data = ma.load_binary(binary_dir / "test_nested_vector_string.bin")
    assert data["config"]["count"] == 3
    assert data["config"]["names"] == ["alpha", "beta", "gamma"]
    print("PASSED")


def test_mixed_types(binary_dir: Path):
    print("Testing mixed types... ", end="", flush=True)
    data = ma.load_binary(binary_dir / "test_mixed_types.bin")
    assert data["name"] == "test"
    assert data["value"] == 42
    assert abs(data["pi"] - 3.14159) < 1e-10
    assert data["tags"] == ["a", "b", "c"]
    assert list(data["data"]) == [1.0, 2.0, 3.0]
    print("PASSED")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python test_mist_archive.py <binary_dir>")
        sys.exit(1)

    binary_dir = Path(sys.argv[1])
    print("=== Python mist_archive Tests ===\n")

    test_vector_string(binary_dir)
    test_vector_string_empty(binary_dir)
    test_nested_vector_string(binary_dir)
    test_mixed_types(binary_dir)

    print("\n=== All tests passed! ===")
